version: '3'
services:
  smashing:
    hostname: smashing
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec smashing start -p 3030 -a '0.0.0.0'"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3030:3030
    volumes:
      - ./smashing:/smashing
    networks:
      - frontend
    environment:
      SMASHING_KEY: ${SMASHING_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      
networks:
  frontend:
    driver: bridge
